/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#cc4900",
        "on-tertiary-fixed": "#00201d",
        "on-tertiary-container": "#f4fffc",
        "error-container": "#ffdad6",
        "on-primary-container": "#fffbff",
        "surface-variant": "#d8e3fb",
        "surface-container": "#e7eeff",
        "on-secondary-fixed-variant": "#683c00",
        "error": "#ba1a1a",
        "tertiary-container": "#008378",
        "tertiary": "#00685f",
        "surface-dim": "#cfdaf2",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-error": "#ffffff",
        "on-background": "#111c2d",
        "on-tertiary": "#ffffff",
        "outline": "#8e7166",
        "surface-container-high": "#dee8ff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#263143",
        "on-primary-fixed": "#370e00",
        "background": "#f9f9ff",
        "surface-container-low": "#f0f3ff",
        "secondary": "#855316",
        "inverse-primary": "#ffb599",
        "surface-bright": "#f9f9ff",
        "primary-fixed-dim": "#ffb599",
        "surface": "#f9f9ff",
        "secondary-fixed-dim": "#fcb973",
        "tertiary-fixed": "#89f5e7",
        "on-error-container": "#93000a",
        "on-surface-variant": "#5a4138",
        "on-surface": "#111c2d",
        "surface-container-highest": "#d8e3fb",
        "on-secondary-container": "#79490b",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffdbce",
        "on-tertiary-fixed-variant": "#005049",
        "inverse-on-surface": "#ecf1ff",
        "secondary-fixed": "#ffdcbd",
        "on-primary-fixed-variant": "#7f2b00",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#ffbc76",
        "primary": "#a33900",
        "outline-variant": "#e2bfb2",
        "on-secondary-fixed": "#2c1600",
        "surface-tint": "#a73a00"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "gutter": "1.5rem",
        "margin": "2rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1.25rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "display-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "title-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "display-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}
